theme: jekyll-theme-architect

# Name of your site (displayed in the header)
name: "erseyang's blog"

# Short bio or description (displayed in the header)
description: "学习与分享 | Study & Share"

# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags